# debugging configuration
debug: true
debug_datasets: false
debug_hypernet: false
debug_hyponet: false

# hypernet configuration
hypernet:
  bert:
    name: bert-base-uncased


# hyponet configuration
hyponet:
  mlp:
    in_dim = 3
    out_dim = 2
    hidden_dim = 4
    depth = 3

tokenizer:
  bert_tokenizer:
    name: bert-base-uncased
    truncation: True
    padding: max_length
    max_length: 256


# dataset configuration
datasets:
  data_root: ./data/

  list_combine_train: # list of datasets to combine
    - diabetes
    - adult

  list_combine_val: # list of datasets to combine for validation
    - adult
    - diabetes
  
  list_combine_test: # list of datasets to combine for testing
    - diabetes
  
  adult:
    name: adult
    save_dir: adult
    test_size: 0.2
    validation_size: 0.1
    n_features: 3
    str_template: "<example>This is the adult income dataset. The final weight is {}. The capital gain is {}. The label is {}.</example>"
    
  diabetes:
    name: diabetes
    save_dir: diabetes
    test_size: 0.2
    validation_size: 0.1
    n_features: 3
    str_template: "<example>This is the diabetes dataset. The final weight is {}. The capital gain is {}. The label is {}.</example>"


