# debugging configuration
debug: true
debug_datasets: false

# dataset configuration
datasets:
  data_root: ./data/

  adult:
    name: adult
    save_dir: adult
    test_size: 0.2
    validation_size: 0.1
    n_features: 3

