# experiment configuration
name: bert
save_dir: './save/'
eval_model: false # "/export/pasand/trans-hyper/save/bert/epoch-last.pth"
wandb_auth: 'wandb_auth.yaml'
wandb_sweep_cfg: 'cfgs/sweeps/sweeptest.yaml'


# debugging configuration
debug: true
debug_datasets: false
debug_hypernet: false
debug_hyponet: false
debug_trainer: false


# hypernet configuration
hypernet:
  name: bert
  model: bert-base-uncased


# hyponet configuration
hyponet:
  model: mlp
  in_dim: 0 # set during runtime
  out_dim: 2
  hidden_dim: 10
  depth: 4


# tokenizer configuration
tokenizer:
  name: bert_tokenizer
  model: bert-base-uncased
  truncation: True
  padding: max_length
  max_length: 512


# trainer configuration
trainer:
  name: bert_trainer
  batch_size: 10
  n_workers: 1
  max_epoch: 25
  eval_epoch: 1
  vis_epoch: 25
  save_epoch: 4
  optimizer:
    name: adam
    args:
      lr: 1.e-5
    


# dataset configuration
datasets:
  data_root: ./data/
  n_shots: 3
  n_queries: 20
  train_ratio: 0.5
  test_ratio: 0.3
  train_size: ""
  test_size: ""
  
  balanced:
    train: True
    val: False
    test: false

  list_combine_train: # list of datasets to combine
    - bank
    - blood
    - calhousing
    - creditg
    - diabetes
    - jungle

  list_combine_val: # list of datasets to combine for validation
    - blood
  
  list_combine_test: # list of datasets to combine for testing
    - income
  
  adult:
    name: adult
    save_dir: adult
    test_size: 0.2
    validation_size: 0.1
    n_features: 3
    str_template: "<example>This is the adult income dataset. The final weight is {}. The capital gain is {}. The label is {}.</example>"
    
  diabetes:
    name: diabetes
    save_dir: diabetes
    test_size: 0.2
    validation_size: 0.1
    n_features: 3
    str_template: "<example>This is the diabetes dataset. The final weight is {}. The capital gain is {}. The label is {}.</example>"

  tabllm:
    raw_data_path: "tabllm/data/datasets"
    txt_data_path: "tabllm/data/datasets_serialized"
    template_dir: "tabllm/templates"


