name: tabpfn-income
note: TabPFN hypernetwork with 8-shot income dataset, without learning rate schedule
save_dir: ./save/
eval_model: false
wandb_auth: wandb_auth.yaml
wandb_sweep_cfg: cfgs/sweeps/sweeptest.yaml
debug: true
debug_datasets: false
debug_hypernet: false
debug_hyponet: false
debug_trainer: false
hypernet:
  name: tabpfn
hyponet:
  model: mlp
  in_dim: 0
  out_dim: 2
  hidden_dim: 10
  depth: 4
trainer:
  name: tabpfn_trainer
  batch_size: 1
  n_workers: 1
  max_epoch: 300
  eval_epoch: 1
  vis_epoch: 25
  save_epoch: 500
  optimizer:
    name: adam
    args:
      lr: 0.0001
datasets:
  data_root: ./data/
  n_shots: 8
  n_queries: 8
  train_ratio: None
  test_ratio: None
  train_size: 1
  val_size: 1
  test_size: 1
  train_permutation: true
  val_permutation: true
  test_permutation: false
  queries_same_as_shots: true
  max_n_features: false
  set_hyponet_indim: true
  balanced:
    train: true
    val: true
    test: false
  list_combine_train:
  - income
  list_combine_val:
  - income
  list_combine_test:
  - income
random_state: true
